# Generated by Django 4.1.7 on 2023-04-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.CharField(choices=[('FAT', 'Father'), ('MOT', 'Mother'), ('BRO', 'Father'), ('SIS', 'Sister'), ('DAU', 'Daughter'), ('SON', 'Son')], max_length=3)),
                ('age', models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
            ],
        ),
    ]
