# Generated by Django 4.1.7 on 2023-04-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_alter_familymember_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='family_member',
            new_name='family_choice',
        ),
        migrations.AddField(
            model_name='actor',
            name='family_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='movie_app.familymember'),
        ),
    ]
