# Generated by Django 4.1.7 on 2023-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_rename_family_member_familymember_family_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_choice',
            field=models.CharField(choices=[('FAT', 'Father'), ('MOT', 'Mother'), ('BRO', 'Brother'), ('SIS', 'Sister'), ('DAU', 'Daughter'), ('SON', 'Son')], max_length=3),
        ),
    ]
