# Generated by Django 4.1.7 on 2023-04-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_remove_actor_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='family_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='movie_app.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
