# Generated by Django 4.1.7 on 2023-04-12 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_actor_family_member_familymember_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PAR', 'Parrot'), ('SNA', 'Snake'), ('FIS', 'Fish')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner', to='movie_app.director')),
            ],
        ),
    ]
