# Generated by Django 4.1.7 on 2023-04-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
    ]
